### PR TITLE
DEP Update minimum composer versions

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/.github/issues/306

### CODE REVIEW

**Comment by GuySartorelli** [comment]
Can you please force push to try get CI to run?

**Comment by emteknetnz** [comment]
I did. Does not seem to want to run :shrug:

**Comment by GuySartorelli** [comment]
Weird - for some reason the workflow is missing
```yml
on:
  pull_request
```
Can you please update it? Or create a card to do that if you wanna handle that separately - but would be nice to get it out of the way while we're looking at it.

**Comment by emteknetnz** [comment]
I did create a pr https://github.com/silverstripe/documentation-lint/pull/13 - however closed it as the only purpose of ci.yml it to dispatch tag-patch-release, which is not appropiate for a pull_request event

**Comment by GuySartorelli** [comment]
Ahhh okay that makes sense.

**Pull request merged**
